### ISSUE TITLE
Plugin doesn't work.

### ISSUE THREAD

**Issue by LlmDl** [thatguycy/WorldDynamics-Engine#24]
It doesn't work plz fix.

**Comment by thatguycy** [comment]
Hello, and thanks for your issue request!
I've review your issue, and I've concluded that the type of error you're experiencing is a [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK). I've further review your profile and have deemed you incapable, please learn a better understanding of plugin development before opening an issue.
Thanks!

![image](https://github.com/thatguycy/WorldDynamics-Engine/assets/33783071/b104c2bc-427d-47c6-9656-4ca04f8f257f)
