### ISSUE TITLE
[Ported] Suggestion: Levels of relations between nations

### ISSUE THREAD

**Issue by stoleyourharvs** [thatguycy/WorldDynamics-Engine#28]
This was originally a suggestion for **TownyAdvanced** but the suggestor(s) have expressed interest in it being added into WDE.
[Towny Issue #6325](https://github.com/TownyAdvanced/Towny/issues/6325) by [Caleston](https://github.com/Caleston)
-----------------------------------------------------------------------------------------------------------------------------------------------------
Towny currently has only 2 types of relations with nations, which are Enemies or Allies. This system could be expanded to include more levels than just black/white, such as:

Unfriendly = Bad relations = Teleports blocked

Friendly = Good relations = No perks
Trade = Trade relations established = Teleportation benefits (lower cost, cooldown, etc)

Allies* = Military Alliance = Current Ally perks + if a nation adds an enemy, it also adds the allies of that enemy as enemies automatically, could help spice things up.
Enemy* = War = Teleports blocked, battles possible

These could all use the same kind of system as Ally/Enemy, adding much more flavor to nation relations and hopefully spicing up geopolitics.
Currently many nations are forming alliances as just trade alliances for ally perks, which confuses geopolitics since you don't really know who is militarily allied. It would be beneficial to separate relation types a bit more, so that nations dont have to be all or nothing to each other.

**Comment by 1ByteBit** [comment]
Another one to consider would be political alliances.

Some balancing would also need to be thought up. For example, there's no reason for people to have friendly relations and not trade relations

**Comment by stoleyourharvs** [comment]
Added in pre-release for v0.2.0, https://github.com/WorldDynamics-MC/WorldDynamics-Engine/releases/tag/v0.2.0.

@1ByteBit open a seperate issue request for your change if you still suggest it!
