### ISSUE TITLE
Cannot use government commands

### ISSUE THREAD

**Issue by Random-User-34** [thatguycy/WorldDynamics-Engine#3]
When attempting to use government commands, it just says "Your nation has no attributes assigned by WDE".

**Comment by thatguycy** [comment]
Fixed here: https://github.com/thatguycy/WorldDynamics-Engine/releases/tag/v0.1.5

Was an oversight on my part, just had an issue where you couldn't set the government type without a government type being set, weird, thanks for contributing!
